#Enables Openthread FTD set
#CONFIG_OPENTHREAD_NORDIC_LIBRARY_FTD=y
#L2 Openthread enabling
CONFIG_NET_L2_OPENTHREAD=y
#Generic networking options
CONFIG_NETWORKING=y
#Enable CoAP protocol
CONFIG_OPENTHREAD_COAP=y

#Network parameters
CONFIG_OPENTHREAD_MANUAL_START=n
CONFIG_OPENTHREAD_NETWORK_NAME="WIA"
CONFIG_OPENTHREAD_PANID=10000
CONFIG_OPENTHREAD_XPANID="fb:02:00:00:ab:cd:00:00"
CONFIG_OPENTHREAD_NETWORKKEY="00:11:22:33:44:55:66:77:88:99:aa:bb:cc:dd:ee:ff"

#Network shell
CONFIG_SHELL=y
CONFIG_OPENTHREAD_SHELL=y
CONFIG_SHELL_ARGC_MAX=26
CONFIG_SHELL_CMD_BUFF_SIZE=416

#Additional params
#CONFIG_MBEDTLS_SHA1_C=n
CONFIG_FPU=y
CONFIG_GPIO=y
CONFIG_JSON_LIBRARY=y
CONFIG_CBPRINTF_FP_SUPPORT=y

CONFIG_CRYPTO=y
CONFIG_CRYPTO_INIT_PRIORITY=90

# Enable TinyCrypt for AES encryption
CONFIG_CRYPTO_TINYCRYPT_SHIM=y
CONFIG_TINYCRYPT=y
CONFIG_TINYCRYPT_AES=y
CONFIG_TINYCRYPT_SHA256=y

# prj.conf

CONFIG_NETWORKING=y
CONFIG_NET_IPV6=y
CONFIG_NET_UDP=y
CONFIG_COAP=y
CONFIG_COAP_LOG_LEVEL_DBG=y
CONFIG_COAP_SERVER=y
CONFIG_OPENTHREAD=y
CONFIG_OPENTHREAD_COAP=y
CONFIG_OPENTHREAD_THREAD_VERSION_1_1=y
CONFIG_LOG=y
CONFIG_GPIO=y
CONFIG_MAIN_STACK_SIZE=10240
